### ISSUE TITLE
Incorrect Statuses

### ISSUE THREAD

**Issue by awickham10** [gomorpheus/morpheus-netbox-plugin#1]
Thank you for the plugin! I've been pondering my own NetBox plugin for a while, but I'm glad that one is officially released now.

I was wondering if the statuses are being set as intended (but maybe it's us using things differently).

In Netbox we use:
| Status | Description |
| -- | -- |
| Active | In use |
| Reserved | Not in use, but reserved for future use |

In Morpheus, it appears that NetBox Active is showing as Reserved in Morpheus and NetBox Reserved is showing as Static. Should this be reversed?

**Comment by BungeBash** [comment]
These were both getting set to reserved by accident.  Resolving next release.
